version: 2
updates:
  - package-ecosystem: "npm"      # ou "pip", "maven", "gradle", "docker", "github-actions", etc.
    directory: "/"
    schedule:
      interval: "daily"          # daily | weekly | monthly | quarterly | semiannually | yearly | cron
      day: "thursday"
      time: "14:50"
      timezone: "Europe/Paris"

